### ISSUE TITLE
dotorg branch 404 error

### ISSUE THREAD

**Issue by webliberty** [swissspidy/gutenberg-i18n-block#5]
In the Plugins section hosted on WordPress.org of the README.md file there is a link to the dotorg branch with a 404 error.

It is not clear how to use translations without .po, .mo, .pot files?

**Comment by swissspidy** [comment]
Thanks for raising this! I will publish an update soon.

Do you want to publish your plugin on WordPress.org then?

**Comment by webliberty** [comment]
I have already published a plugin [Simple Note](https://wordpress.org/plugins/simple-note/) on WordPress.org, but I could not use the function wp_set_script_translations( 'my-handle', 'my-domain' ); for translation

**Comment by Viper007Bond** [comment]
Any updates here? People have translated my plugin's block via translate.wordpress.org and I'd love to learn how to properly make use of the translations (`wp_set_script_translations()` doesn't seem to automatically work).

**Comment by swissspidy** [comment]
FYI the issue I was referring to is https://meta.trac.wordpress.org/ticket/3876. THat's probably the best place to look for updates.

**Comment by swissspidy** [comment]
Closing as I removed references to the dotorg branch for now.
