### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by prajaktagadhave123** [swissspidy/gutenberg-i18n-block#7]
Hello,

Can you please tell me the steps to to create pot file like this - `gutenberg-i18n-block-js.pot`.

What steps I need to follow to create javascript pot file for my plugins?

Also, I am getting this error - https://monosnap.com/file/54fNulPIKsyDKLpEOVipFagk4hp0Fv

**Comment by swissspidy** [comment]
It depends on whether you are using Babel or not.

As for your error message, make sure you are using the latest version of WP-CLI (2.1.0 at the moment). To get the absolute latest version of that i18n command itself, run `wp package install git@github.com:wp-cli/i18n-command.git`.

Assuming you are using the current master branch of this repo, `npm run build:js` and `npm run build:pot` should work fine.
